partialize: (s) => ({
        theme: s.theme,
        customVehicles: s.customVehicles,
        selectedVehicleId: s.selectedVehicleId,
        cargo: s.cargo,
        settings: s.settings,
        result: s.result,
        pristine: s.pristine,
        activeVariant: s.activeVariant,
        sessions: s.sessions,
        loadingPoints: s.loadingPoints,
        unloadingPoints: s.unloadingPoints,
      }),